//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AliciaEnElMundoVegano.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Index {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Index() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AliciaEnElMundoVegano.Resources.Index", typeof(Index).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our youth. Our environment. Our society. We want to help change bad habits and encourage healthy ones by moving towards a better all-rounded diet. We also strive to give back to the community, environment and nature..
        /// </summary>
        public static string Cause {
            get {
                return ResourceManager.GetString("Cause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improve diets by transitioning towards veganism.
        /// </summary>
        public static string Objectives1 {
            get {
                return ResourceManager.GetString("Objectives1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cultivate appreciation and admiration for the nature around us.
        /// </summary>
        public static string Objectives2 {
            get {
                return ResourceManager.GetString("Objectives2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encourage participating in voluntary programs.
        /// </summary>
        public static string Objectives3 {
            get {
                return ResourceManager.GetString("Objectives3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who are we?.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cause.
        /// </summary>
        public static string SubHeading1 {
            get {
                return ResourceManager.GetString("SubHeading1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vision.
        /// </summary>
        public static string SubHeading2 {
            get {
                return ResourceManager.GetString("SubHeading2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goals.
        /// </summary>
        public static string SubHeading3 {
            get {
                return ResourceManager.GetString("SubHeading3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We at Alicia En El Mundo Vegano envision a healthier, greener world in which our current and future generations take care of their surroundings and themselves through ameliorated lifestyles..
        /// </summary>
        public static string Vision {
            get {
                return ResourceManager.GetString("Vision", resourceCulture);
            }
        }
    }
}
