//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AliciaEnElMundoVegano.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Recipes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Recipes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AliciaEnElMundoVegano.Resources.Recipes", typeof(Recipes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our youth. Our environment. Our society. We want to help change bad habits and encourage healthy ones by moving towards a better all-rounded diet. We also strive to give back to the community, environment and nature..
        /// </summary>
        public static string PageTitle
        {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Improve diets by transitioning towards veganism.
        /// </summary>
        public static string R1Content
        {
            get {
                return ResourceManager.GetString("R1Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cultivate appreciation and admiration for the nature around us.
        /// </summary>
        public static string R1Title
        {
            get {
                return ResourceManager.GetString("R1Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encourage participating in voluntary programs.
        /// </summary>
        public static string R2Content
        {
            get {
                return ResourceManager.GetString("R2Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who are we?.
        /// </summary>
        public static string R2Title
        {
            get {
                return ResourceManager.GetString("R2Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cause.
        /// </summary>
        public static string R3Content
        {
            get {
                return ResourceManager.GetString("R3Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vision.
        /// </summary>
        public static string R3Title
        {
            get {
                return ResourceManager.GetString("R3Title", resourceCulture);
            }
        }
        
    }
}
